### ISSUE TITLE
Implementation with reanimated v2 and navigation v6??

### ISSUE THREAD

**Issue by zoobibackups** [react-ui-kit/freebies#27]
Can you update it to the latest versions of :

react-native, // .67
react-native-reanimated // latest
@react-navigation/drawer // v6 currently

**Comment by hetmann** [comment]
@zoobibackups sure thing :)

**Comment by hetmann** [comment]
@zoobibackups login is upgraded and you can check the PR https://github.com/react-ui-kit/freebies/pull/29/files

**Comment by zoobibackups** [comment]
Thanks alot
